# Generated by Django 4.0 on 2022-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
